import {
  ComputerDesktopIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  GiftIcon,
  TruckIcon,
  CreditCardIcon,
  ArchiveBoxIcon,
  UserGroupIcon,
  StarIcon,
  LightBulbIcon,
  ChartPieIcon,
  UserCircleIcon,
  Cog8ToothIcon,
} from "@heroicons/react/24/outline";
import { SIDEBAR_ROUTES } from "@/utils/routes";

export const sidebarNavLinks = {
  links: [
    { name: "Dashboard", href: SIDEBAR_ROUTES.DASHBOARD },
    { name: "Products", href: SIDEBAR_ROUTES.PRODUCTS },
    { name: "Orders", href: SIDEBAR_ROUTES.ORDERS },
    { name: "Offers", href: SIDEBAR_ROUTES.OFFERS },
    { name: "Transactions", href: SIDEBAR_ROUTES.TRANSACTIONS },
    { name: "Shipping", href: SIDEBAR_ROUTES.SHIPPING },
    { name: "Inventory", href: SIDEBAR_ROUTES.INVENTORY },
    { name: "Customers", href: SIDEBAR_ROUTES.CUSTOMERS },
    { name: "Ratings", href: SIDEBAR_ROUTES.RATINGS },
    { name: "Statistics", href: SIDEBAR_ROUTES.STATISTICS },
    { name: "Manage Account", href: SIDEBAR_ROUTES.MANAGE_ACCOUNT },
    { name: "Settings", href: SIDEBAR_ROUTES.SETTINGS },
    { name: "Help", href: SIDEBAR_ROUTES.HELP },
  ],
  icons: [
    { name: "DashboardIcon", atr: ComputerDesktopIcon },
    { name: "ProductsIcon", atr: ShoppingBagIcon },
    { name: "OrdersIcon", atr: ShoppingCartIcon },
    { name: "OffersIcon", atr: GiftIcon },
    { name: "TransactionsIcon", atr: CreditCardIcon },
    { name: "ShippingIcon", atr: TruckIcon },
    { name: "InventoryIcon", atr: ArchiveBoxIcon },
    { name: "CustomersIcon", atr: UserGroupIcon },
    { name: "RatingsIcon", atr: StarIcon },
    { name: "StatisticsIcon", atr: ChartPieIcon },
    { name: "ManageAccountIcon", atr: UserCircleIcon },
    { name: "SettingsIcon", atr: Cog8ToothIcon },
    { name: "HelpIcon", atr: LightBulbIcon },
  ],
};
